direction: left

zabbix: Zabbix server {
  zabbix_db: pgsql: {shape: cylinder}
  zabbix_server: zserver: {shape: rectangle}
  zabbix_server <-> zabbix_db
}

prom: Prometheus server {
  prom_db: victoria: {shape: cylinder}
  prom_server: grafana: {shape: rectangle}
  apps: Application and services {shape: cloud}
  prom_exporter: exporters

  apps -> prom_exporter
  prom_server <-> prom_db
  prom_exporter -> prom_server
}

prod: Production stage {
  # zabbix 
  zproxy_db: mysql: {shape: cylinder}
  zproxy_server: zproxy: {shape: rectangle}
  hardware: Hardwaren and services {shape: rectangle}
  # prom
  apps: Application and services {shape: cloud}
  prom_exporter: exporters
  prom_exporter <- apps
  zproxy_server <-> zproxy_db
  hardware -> zproxy_server
}

preprod: Preprod stage {
  zproxy_db: mysql: {shape: cylinder}
  zproxy_server: zproxy: {shape: rectangle}
  hardware: Hardwaren and services {shape: rectangle}
  # prom
  apps: Application and services {shape: cloud}
  prom_exporter: exporters
  prom_exporter <- apps
  zproxy_server <-> zproxy_db
  hardware -> zproxy_server
}

test: Test stage {
  zproxy_db: mysql: {shape: cylinder}
  zproxy_server: zproxy: {shape: rectangle}
  hardware: Hardwaren and services {shape: rectangle}
  # prom
  apps: Application and services {shape: cloud}
  prom_exporter: exporters
  prom_exporter <- apps
  zproxy_server <-> zproxy_db
  hardware -> zproxy_server
}

dev: {
  zproxy_db: mysql: {shape: cylinder}
  zproxy_server: zproxy: {shape: rectangle}
  hardware: Hardwaren and services {shape: rectangle}
  # prom
  apps: Application and services {shape: cloud}
  prom_exporter: exporters
  prom_exporter <- apps
  zproxy_server <-> zproxy_db
  hardware -> zproxy_server
}

office: Office space {
  style: {stroke: red}
  zproxy_db: mysql: {shape: cylinder}
  zproxy_server: zproxy: {shape: rectangle}
  hardware: Hardwaren and services {shape: rectangle}
  # prom
  apps: Application and services {shape: cloud}
  prom_exporter: exporters
  prom_exporter_proxy: exporter_proxy
  apps -> prom_exporter
  prom_exporter -> prom_exporter_proxy
  zproxy_server <-> zproxy_db
  hardware -> zproxy_server
}

# Stage to zabbix
zabbix.zabbix_server <-> prod.zproxy_server
zabbix.zabbix_server <-> preprod.zproxy_server
zabbix.zabbix_server <-> test.zproxy_server
zabbix.zabbix_server <-> dev.zproxy_server
zabbix.zabbix_server -> office.zproxy_server: {style: {stroke: red}}

# zabbix - prom integration
zabbix.zabbix_server <-> prom.prom_server

# Stege to prom
prod.prom_exporter -> prom.prom_server
preprod.prom_exporter -> prom.prom_server
dev.prom_exporter -> prom.prom_server
test.prom_exporter -> prom.prom_server
office.prom_exporter_proxy -> prom.prom_server: {style: {stroke: red}}
